### ISSUE TITLE
mirror_repo() with overwrite = FALSE: Should this succeed/fail repo by repo?

### ISSUE THREAD

**Issue by rpruim** [rundel/ghclass#101]
I'm wondering if the following idea would make sense, at least as an option. It is useful for adding a new student after the assignment has been created for other students.

In `repo_mirror()` you have

```r
    n_commits = table(repo_commits(target_repo)[["repo"]])
    # omitted lines
    if (!overwrite & any(n_commits > 1)) {
        usethis::ui_stop(c("The following {usethis::ui_code('target_repo')}s have more than a single initialization commit:", 
            "\t{usethis::ui_value(target_repo[n_commits > 1])}.", 
            "This process will permanently overwrite these repositories. If you are sure this is what", 
            "you want to do re-run this function with {usethis::ui_code('overwrite = TRUE')}"))
    }
```
This fails for **all** repositories if **any** have user commits and `overwrite == FALSE`.

I'm wondering if something like this (or an equivalent) could be inserted:

```r
target_repo <- 
  repo_commits(target_repo) %>% 
  group_by(repo) %>% 
  summarise(n = n()) %>% 
  filter(n <= 1) %>% 
  pull(repo)
```

This would allow mirroring only to repos where this is non-destructive.  One could perhaps still include messaging about the repos not being updated.

I'm currently using code like this to preprocess the `target_repo` argument of `mirror_repo()` to get this effect.

**Comment by rundel** [comment]
I think this makes sense, I've come up with a revised implementation that moves both checks inside of the purrr loop. Can you take a look at the repo_mirror_early_stop branch and see if that works for you as well?

**Comment by rpruim** [comment]
Seems to be working (but now that I've done the push for all of my students, I don't have a test case for successful push to the repositories with only a single initialization commit).

I like the messaging, including the number of commits to each of the repos.

Thanks.

**Comment by rundel** [comment]
I'll merge this into master and close this, if anything comes up feel free to reopen
