### ISSUE TITLE
master is now main (for new repos)

### ISSUE THREAD

**Issue by nicholasjhorton** [rundel/ghclass#112]
Yippee for the change (GitHub wide). 

But it means that one needs to add 'branch = "main"' occasionally (e.g., `local_repo_clone()`).  Perhaps it might be helpful to add this to the vignette?

**Comment by rundel** [comment]
Definitely agree - we've added a brief bit of text to the readme and more details in the FAQ of the vignette to cover the basics and provide some suggestions for users.
