### ISSUE TITLE
org_create_assignment issue (probably change from master to main)

### ISSUE THREAD

**Issue by pefreeman** [rundel/ghclass#114]
With GitHub's recent push to rename "master" to "main" for all newly created repos, things are starting to break :(

I reinstalled ghclass this morning and ran org_create_assignment(). After creating the student repos, I got the following error message:

Error in arg_is_chr(repo, branch) : 
  argument "branch" is missing, with no default

As I cannot specify branch="main," the crash occurs. (I think; this seems the logical conclusion.) I cannot find the offending call in the code base; perhaps it is in gert in one of the cloning functions. I have tried to update gert from 0.3 to 1.0 in case somehow this is fixed there but I cannot install a binary and I'm having issues installing from source. If updating gert fixes this just close this issue :)

In the meantime, I will attempt other means to clone today's lab to the student directories. I warn the students that the tidyverse and GitHub are both the Wild West, and this is a good example of how things can change fast.

Thanks.

**Comment by nicholasjhorton** [comment]
I didn't have any issues when I ran `org_create_assignment()`.  But I did run into problems when I tried to clone the repos, and I had to add `'branch = "main"'` as an option to `local_repo_clone()`.  I don't know if that will help on your end.

See https://github.com/rundel/ghclass/issues/112

**Comment by rundel** [comment]
I think I may know what is causing this - but I will need to double check. Peter, are you using the `repo_mirror` and not `repo_mirror_template`?

**Comment by pefreeman** [comment]
Yes, I'm using repo_mirror.

**Comment by pefreeman** [comment]
Nick: I think that will help, thanks, but I may also need to change to repo_mirror_template before implementing that. Awaiting Colin's response.

**Comment by rundel** [comment]
I think I found the issue - should not be a major fix. The problem function is `repo_n_commits` which was being used to see if a repo was potentially overwritable, but this requires a branch to be specified.

**Comment by pefreeman** [comment]
I restarted the process and used repo_set_template() before calling org_create_assignment(), and everything appeared to work fine. Also did a test retrieval of the repo with branch="main" (thanks Nick!) and that worked fine too.

Upshot: while you probably want to fix repo_n_commits() it is no longer critical (for me at least :). Thx!

**Comment by rundel** [comment]
Glad to hear things worked with the template repo - I think I've fixed the issues with repo_n_commit and hence the repo_mirror path. if you get a chance to try it let me know.

**Comment by pefreeman** [comment]
For the first lab next week, I can leave out the repo_set_template() step and see if assignment creation goes to completion.

**Comment by rundel** [comment]
Sounds good, I'll leave this open for now then.

**Comment by pefreeman** [comment]
Bug fix confirmed this morning: when I run org_create_assignment() *without* running repo_set_template() first, it now runs fine to completion. (But I'll use repo_set_template() in the future anyway.) You can close this issue. Thx!
