### ISSUE TITLE
repo_commits() returns only the last 30 entries

### ISSUE THREAD

**Issue by AlexRieber** [rundel/ghclass#118]
When i run repo_commits() on a repo i get only the last 30 commits instead of the full list of commits by each contributor for that repo.

**Comment by rundel** [comment]
Odd, I am not seeing that behavior - when I check against this repo I get the following:

```r
dim( ghclass::repo_commits("rundel/ghclass") )
## [1] 999   6
```

which is the current # of commits.

**Comment by AlexRieber** [comment]
Just reinstalled ghclass and all dependencies and got the correct output...sorry for the inconvenience!

**Comment by rundel** [comment]
No worries, glad to hear everything is working as expected now
