### ISSUE TITLE
can't delete repo?

### ISSUE THREAD

**Issue by beanumber** [rundel/ghclass#120]
``` r
library(ghclass)
repo <- "sds192-f20/mp4-delta-c"
repo_collaborators(repo)
#> # A tibble: 1 x 5
#>   repo                   username  pull  push  admin
#>   <chr>                  <chr>     <lgl> <lgl> <lgl>
#> 1 sds192-f20/mp4-delta-c beanumber TRUE  TRUE  TRUE
repo_delete(repo)
#> This command will delete the following repositories permanently: 'sds192-f20/mp4-delta-c'.
#> 
#> 1: Yes
#> 2: No
#> 
#> Selection: 1
#> x Failed to delete repo 'sds192-f20/mp4-delta-c'.
#> └─GitHub API error (403): 403 Forbidden
#>   ├─ API message: Must have admin rights to Repository.
#>   └─ API docs: https://docs.github.com/rest/reference/repos#delete-a-repository
```

<sup>Created on 2020-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Can you think of any reason why this would occur? 

It's a problem for me because if I make a mistake, I can't easily clean up after myself.

**Comment by rundel** [comment]
My guess is that there is an issue with the scopes for the PAT you are using, can you run the following and post what you get:

```r
gh::gh_whoami(.token = ghclass::github_get_token())$scopes
```

`delete_repo` should be in the list.

**Comment by beanumber** [comment]
Bang! I only see 
```
"gist, repo, workflow"
```

Where does that get set and how can I change it?

**Comment by mine-cetinkaya-rundel** [comment]
Settings > Developer settings > Personal access tokens. You can click on the PAT and change its scope.

**Comment by beanumber** [comment]
Amazing. Thank you!

**Comment by rundel** [comment]
I generally find the oauth scopes quite opaque and so this is an easy problem to have - I think it would be straight forward to  add a `github_sitrep` function which would report on the state of the critical scopes.
