### ISSUE TITLE
local_repo_add with flag "--all" possible?

### ISSUE THREAD

**Issue by AlexRieber** [rundel/ghclass#125]
This might be an issue with gert::git_add(), but is there a possibility to include the "--all" flag to resemble "git add --all" in local_repo_add()?

An example when this would be helpful:
- I set up some git repos
- I clone them locally and put in some subdirectories with various files in each subdirectory
- Now i want to push all to my remote directory, here the "--all" flag would be nice to stage all files first, even those in the subdirectories.

**Comment by rundel** [comment]
In looking at the code, it seems like the default for `local_repo_add` is for `files = "."` which should be adding everything (at least what is listed git status). Can you see if that works for your use case?

**Comment by AlexRieber** [comment]
unfortunately i get always the same error: 
x Failed to add files 'peer27/', 'peer52/', and 'peer57/' to 'peer27'.
When i look at git_status I see only the sub-directories "peer27/", "peer52/" and "peer57" as "new" but cannot add them as they are no files but directories.
I had a look into the gert::git_add() and the Error message seems to be generated by gert.

The "files = '.' " just adds all _files_ in the _current directory_, but **not in subdirectories**, which would be feasible when using "git add --all".

**Comment by rundel** [comment]
I've just merged Finn's fix - can you see if this resolves the issue for you?

**Comment by AlexRieber** [comment]
Works like a charm, thanks!

**Comment by rundel** [comment]
Glad to hear it @finnlindgren thanks for the fix

**Comment by finnlindgren** [comment]
I thought my fix would only fix one aspect of it, but great if it actually solved this issue!
