### ISSUE TITLE
Better error for creating teams/repos that already exist

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rundel/ghclass#14]
If a team or repo already exists in the org and I try to create it again, I get an error like

```
# for team
GitHub API error (422): 422 Unprocessable Entity - Validation Failed
# for repo
GitHub API error (422): 422 Unprocessable Entity - Repository creation failed.
```

It would be better if the error said the actual issue -- "team/repo already exists, not recreated", or something along those lines.

**Comment by rundel** [comment]
Fixed
