### ISSUE TITLE
add_werker error message

### ISSUE THREAD

**Issue by merliseclyde** [rundel/ghclass#15]
If the repo does not exist, then add_werker errors as in example below

`> add_wercker(repo="STA521-F18/lab1-merlise", wercker_org="STA521-F18")
Creating wercker app for STA521-F18/lab1-merlise ...
Error in wercker_api_add_app(repo, provider, privacy, org_id, key) : 
  Forbidden (HTTP 403).
`

Feature addition: test if the repo does not exist and provide a message like "repo does not exist" that is more informative.
(use get_repos to check???, but with sanitized error message?)

**Comment by rundel** [comment]
Tried to clean this up, but the wercker API is still flaky. Also wercker stuff has been cut out and moved into a separate package `rundel/wercker`.
