### ISSUE TITLE
add_files(): Include functionality to check for modifications

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#17]
Should add_files() do a check to see whether a file on the target repository (i.e. students' work) has been modified since the instructor's last commit to avoid accidentally over-writing students' work?

The function could include a parameter called `overwrite = T` to obtain the current behavior. 

If `overwrite = F` and there are modifications, execution could pause and output a message detailing which documents have been modified since the last commit by the instructor.

**Comment by rundel** [comment]
This is definitely a good idea as I've personally wiped out several repos this semester by not being careful about this specifically.

**Comment by thereseanders** [comment]
The same thing happens with `mirror_repo()`. Files in the target repo are over-written with files in the source repo.

More explicit messaging or interaction between the user and the execution of the function (e.g. `pause`) could help. Should I open a separate issue to keep track of this?

**Comment by thereseanders** [comment]
Upon discussion with @mine-cetinkaya-rundel, I will implement the following changes:
1. Add a parameter to `add_files`, `mirror_repo`, and related functions called `overwrite`.
2. Set `overwrite = F` as the default.
3. Implement a check to see whether **any** student (i.e. organization member) has modified **any** file in the target repo since the last commit. 
4. If there was a modification since the last commit, deny adding files and add messaging: 
> Target repository was modified by a student since the last commit. 
Running this function will overwrite student modifications. 
If you are certain you want to continue, re-run upon setting overwrite = T.

**Comment by mine-cetinkaya-rundel** [comment]
For the message, last sentence should read "re-run with overwrite = TRUE".

**Comment by rundel** [comment]
I think this all makes sense, and I like the overwrite argument. Internally, I think the logic for mirror repo will need to be somewhat different since there is the potential of some files being overwritten and others not. add_files should be straight forward as we're already checking for the existence of the file on the github repo.

**Comment by thereseanders** [comment]
Implemented through #37
