### ISSUE TITLE
repo parameter combination or org and repo name

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#19]
For many ghclass functions, the repo parameter has the form "owner/name." This creates a number of behaviors that are confusing.

For example 
- `rename_repo("ghclass-test/resources", "literature")` renames the "resources" repo "literature, but 
- `rename_repo("ghclass-test/resources", "ghclass-test/literature")` renames it "ghclass-test-literature."

Should I change the parameters to force users to always specify the organization and repo_name separately? For example:
- `rename_repo(org = "ghclass-test", repo_source = "resources", repo_target =  "literature")`

**Comment by thereseanders** [comment]
Along these lines, should we mirror the naming conventions from the GitHub API, i.e. "owner" instead of "org" and "name" for the repo name instead of "repo" or "repos"?

**Comment by thereseanders** [comment]
I created an [overview](https://docs.google.com/spreadsheets/d/1iPPi-3FtnLMICZJXgyhpxuht44AseogOx2Xzaqtedyk/edit?usp=sharing) of the current usage of the combination of the `org` and `repo` (i.e. repository name) parameters.

- [ ] Change all `repos` to `repo` (if applicable).
- [ ] Decide whether `repo` means the entire "org/repo" character string or just the repository name.
- [ ] Decide whether to use single "org/repo" character string to identify repository or separate `org` and `name` parameters.
- [ ] Decide whether to use `org` or `owner` as the parameter name.

**Comment by mine-cetinkaya-rundel** [comment]
I think we decided on this so let me summarize here and tell me if you disagree: `repo` means `"org/repo"` everywhere and in the docs we say "in `owner/name` format".
