### ISSUE TITLE
check_repo() does not do exact string matching

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#20]
`check_repo()` does not undertake exact string matching to test whether a repo exists. Suffixes, but not prefixes, are ignored.

The organization "ghclass-test" contains a repository "testing_new". 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/26805373/58725079-24a90a80-8393-11e9-9f88-f0b369d3cae7.png">

The current version of `check_repo()` returns the following behaviors:
- `check_repo("ghclass-test/testing_new") = T`
- `check_repo("ghclass-test/testing") = T` -> **This shouldn't happen?!**
- `check_repo("ghclass-test/testing_") = F`
- `check_repo("ghclass-test/testing-new") = F`
- `check_repo("ghclass-test/new_testing") = F`
- `check_repo("ghclass-test/test") = F`

**Comment by thereseanders** [comment]
Actually, I cannot re-create the issue when the repos "ghclass-test/hw1_Mel" and "ghclass-test/hw1_Dave" exits, `check_repo("ghclass-test/hw1") = F`

**Comment by rundel** [comment]
Not sure if this fixed things, can you take a look?

**Comment by mine-cetinkaya-rundel** [comment]
I believe this issue was due to repo renaming, so the function needs to check for current name only of repos, and ignore historical names.

**Comment by rundel** [comment]
Interesting edge case that I hadn't considered. It should be possible to detect something like this based on some of the data being returned by the API. Maybe we can include an additional argument like `strict=TRUE` or `redirect=FALSE`?

**Comment by thereseanders** [comment]
I wrote an add-on to the previous version of `check_repo` that uses `"GET /repositories/:id"` to check whether the repo was renamed. I am currently trying to integrate it into the new version of check_repo based on Colin's [changes](https://github.com/rundel/ghclass/commit/0d4f5d88e3788e3ab0b1317aa89acdd8c75347e5), without running the `gh` query twice.

@rundel to that end, I am thinking of re-integrating the functionality of `github_api_repo_exists` into `check_repo`. Any thoughts?

**Comment by thereseanders** [comment]
#31 implements a vectorized version of `check_repo` that checks whether the user-supplied repository has been renamed and does now exist under a new name.

`check_repo` includes a new parameter `redirect`. 
- If `redirect = F` and the user-supplied repository name existed previously but has since been renamed, `check_repo` returns `FALSE`.
- If `redirect = T` and the user-supplied repository name existed previously but has since been renamed, `check_repo` returns `TRUE`.

The old version `check_repos` has been deprecated.
