### ISSUE TITLE
get_collaborators and get_repo_collaborators functional duplicates

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#25]
`get_collaborators` and `get_repo_collaborators` in the `repo.R` file appear to be functionally extremely similar. Differences:

1. `get_repo_collaborators` relies on `github_api_get_repo_collaborators` (i.e. a `gh` object of lists) to extract collaborator user names from the `collaborators` API endpoint, while `get_collaborators` internalizes the step.
2. `get_collaborators` incorporates the `get_admins` function to allow Admin users to be excluded from the list of collaborators.
3. `get_collaborators` informs user if collaborators could not be retrieved.

I propose to 
- [x] keep `get_collaborators`
- [x] deprecate `get_repo_collaborators `
- [x] If we want to incorporate `github_api_get_repo_collaborators` into `get_collaborators`, change `gh()` inside `github_api_get_repo_collaborators` to `safe_gh()`?

**Comment by mine-cetinkaya-rundel** [comment]
Good catch, there is definitely duplication here.

Your steps sound good:
- The function name should be `get_collaborators`
- Per #26 we want to keep the `github_api_get_repo_collaborators()` functionality (though that functions name should be changed to `github_api_get_collaborators()` to match, so move that over into the `get_collaborators()` function as you proposed
- The functionality for separate handling of admins is useful (often we want to know about students, not admins that get automatically added to the teams) but let's do this as an argument in the `get_collaborators()` function called `include_admins` that is set to `TRUE` by default. If user changes it to `FALSE` then the function result should not list the admins in the organization.

**Comment by thereseanders** [comment]
Implemented as per #31.
