### ISSUE TITLE
Wrap all calls to the gh package in functions with `github_api_*` prefix

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rundel/ghclass#26]
A systematic review of package functions that call functions from the gh package is needed to wrap all calls to the GitHub API with functions that start with the `github_api_*` prefix.

This will be helpful if in the future the package gains functionality for working with GitLab, GitHub Enterprise, etc. It will make it easier to figure out which functions will need to be updated.

@thereseanders You don't need to worry about the systematic review right now, but this is useful to take a note of for functions you're already updating for other reasons as well as new peer review functions we will be writing.

**Comment by mine-cetinkaya-rundel** [comment]
Also make sure all uses of `safe_gh()` are removed

**Comment by rundel** [comment]
I think this is now wrapped up
