### ISSUE TITLE
Deprecate or alias plural function names

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#32]
Should function names changed from singular to plural be deprecated (see `check_repos` in #31) or aliased (see `get_repos` in `org.R`)?

Within `repo.R` or `org.R`, this applies to the following remaining functions.
- [x] `github_api_get_repos`
- [x] `get_repos`
- [x] `github_api_get_collaborators`
- [x] `get_collaborators`
- [x] `get_admins`
- [x] `github_api_get_members`
- [x] `get_members`
- [x] `github_api_get_invitations`
- [x] `get_pending_members`

**Comment by mine-cetinkaya-rundel** [comment]
Let's make all of these singular.
- Exported functions should be properly deprecated.
- Non-exported functions can just be changed.
