### ISSUE TITLE
invite_user message and re-instated membership

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#35]
`invite_user` currently outputs the message below after canceling a user's membership and subsequently re-inviting them. 
> [user] already part of [owner] ...

I believe this is due to former member's data being [saved](https://help.github.com/en/articles/removing-a-member-from-your-organization) for three months and the membership being "reinstated."

Is there a way to distinguish whether a user's membership is newly created or reinstated through the GitHub API and the message in `invite_user`?

**Comment by rundel** [comment]
Can you check the current version of the function and let me know if it works how you expect or if it needs additonal tweaking?

**Comment by thereseanders** [comment]
I made some changes to the function, merging your and my version in #36. 

This does not add the desired functionality to allow giving pending users a nudge to accept the invitation, but it does fix the unused argument issue. 

I added messaging functionality for three groups of users:
1. New members
2. Existing members
3. Pending members

**Comment by mine-cetinkaya-rundel** [comment]
Now that the messaging is better with @thereseanders' updates, and there doesn't seem to be an obvious way to nudge a pending user, we'll call this good for the time being.
