### ISSUE TITLE
Deprecation 

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rundel/ghclass#38]
1. No need to deprecate `github_api_*` functions. The warnings can be confusing for users since user never directly calls them. I'll do this in one sweep throughout the package when open PRs are closed.

2. For deprecated functions the message should read as follows

`OLD_FUNCTION is deprecated and will be removed in the next version. Use NEW_FUNCTION instead.`

So the only change is the "is deprecated and" bit, since R doesn't by default print that the reason for the warning is deprecation.

**Comment by thereseanders** [comment]
Implemented (plus additional formatting changes in #41)
