### ISSUE TITLE
file versus path

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#60]
Currently, parameter names for files are not consistent across functions (some use `path`, others use `file`).

I suggest to use:

`path` within functions that make calls to the GitHub API (to match parameter name in API)
- [x] `repo_put_file()` (currently `path`)
- [x] `repo_get_file()` (currently `file`)
- [x] `repo_modify_file()` (currently `file`)
- [x] `find_file()` (currently `file`)
- [x] `file_exists()` (currently `file`)
- [x] `check_file_modification()` (currently `path`)
- [x] `get_commits()` (currently `path`)
- [x] `repo_files()` outputs `path` indirectly through mapping of GitHub parameter names. 
- [x] `format_repo()` (currently `file`)
- [ ] `peer_assign()` (currently `file`)
- [ ] `peer_create_issue()` (currently `path`)
- [ ] `peer_return()` (currently `path`)
- [x] `extract_content()` (currently `file`)
- [x] `github_api_repo_get_file` (currently `file`)

`local_path` within functions that reference local files
- [x] `repo_add_file()` (currently `file`)
- [ ] `peer_add_file()` (currently `file`)

**Comment by mine-cetinkaya-rundel** [comment]
Suggestions sound good!

**Comment by thereseanders** [comment]
@mine-cetinkaya-rundel  or @rundel, could you briefly comment on the two cases below that are not as clear-cut?

- [ ] `local_repo`: currently `files`; change to `local_path` (note change to singular) for consistency?
- [ ] `styler_repo`: currently `files`; change to `path` (note change to singular) for consistency?


FYI, I kept `files` as an internal object name, for example in `file_exists`, and changed only user-facing attribute names. See two examples below:
``` r
file_exists = function(repo, path, branch = "master"){

  files = repo_files(repo, branch)

  purrr::map_lgl(path, ~.x %in% files[["path"]])

}

repo_get_readme = function(repo, branch = "master") {
  stopifnot(length(repo) == 1)
  stopifnot(length(branch) == 1)

  file = purrr::possibly(github_api_repo_get_readme, NULL)(repo, branch)

  extract_content(file)
}
```

**Comment by rundel** [comment]
I think we've got all of these changed now, I'm going to close this for now but let me know if you find any lingering `file`s
