### ISSUE TITLE
Naming inconsistency of GitHub helper functions

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#62]
Some `github_api_*` functions are named inconsistently. 

Currently, most `github_api_*` functions have the form `github_api_[who]_[what]`, for example  `github_api_branch_create()` and `github_api_branch_delete()`.  This suggests the  following renaming:

- `github_api_user_add` <= `github_api_add_user`
- `github_api_team_add` <= `github_api_add_team`
- `github_api_invitations_get` <= `github_api_get_invitations`
- `github_api_pull_request_create` <= `github_api_create_pull_request`

Note that this is not consistent with the naming of user-facing function, i.e. `repo_add_file()`, `repo_put_file`. Thus, I could also imagine a re-naming of `github_api_*` functions the other way around, for example

- `github_api_create_branch` <= `github_api_branch_create`
- `github_api_create_repo` <= `github_api_repo_create`

Either way, it should be consistent.

**Comment by mine-cetinkaya-rundel** [comment]
I agree with the consistency comment, and it seems to me like the latter option would match the naming convention we're using in the exported functions.

Thoughts @rundel?

**Comment by rundel** [comment]
I think #67 addresses this, did I miss any?

**Comment by thereseanders** [comment]
The following functions should be changed as well

In `github_util.R`
- `github_api_commits_get()` <= `github_api_get_commits()`

In `team_pending_members.R`
- `github_api_team_pending()` <= `github_api_team_pending_members()` (to match `github_api_org_pending()`)

In `repo_exists.R`
- `github_api_repo_get()` <= `github_api_get_repo()`

In `user_exists.R`
- `github_api_user_get()` <= `github_api_get_user()`

In `repo_watch.R`
- `github_api_subscription_set()` <= `github_api_set_subscription()`

This would have to be changed in many places, and is a very low level function, thus I am not sure: in `ZZZ.R`:
- `github_api_limit_get()` <= `get_github_api_limit()`

**Comment by rundel** [comment]
I think I've got all of these now, I've gone for a slightly different naming scheme in some cases but it should hopefully be more consistent.
