### ISSUE TITLE
repo_create does not add team to repo

### ISSUE THREAD

**Issue by merliseclyde** [rundel/ghclass#75]
The deprecated version create_repo created the repo and added the repo to the team given by the name argument.  The current version creates the repo using the team name, but does not add the team/members to the repo, requiring the use of an additional function repo_add_team to add the team to the repo. Using  functions org_repos and org_teams to provide the arguments does require additional parsing to ensure that the team-repos and team names are matched accordingly.

**Comment by rundel** [comment]
I’ve tried to modularize things so that there is one action per function - there is now a new meta function called org_create_assignment (https://rundel.github.io/ghclass/reference/org_create_assignment.html) which handles everything.

-Colin

**Comment by merliseclyde** [comment]
Perfect !!! Will update scripts accordingly...

Sent from my iPhone

On Sep 13, 2019, at 2:50 PM, Colin Rundel <notifications@github.com<mailto:notifications@github.com>> wrote:

I’ve tried to modularize things so that there is one action per function - there is now a new meta function called org_create_assignment (https://rundel.github.io/ghclass/reference/org_create_assignment.html<https://urldefense.proofpoint.com/v2/url?u=https-3A__rundel.github.io_ghclass_reference_org-5Fcreate-5Fassignment.html&d=DwQFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=x3pHRqWA0t5CXMKfReZn7ZqLj13kFVUgFfTldRCztdQ&m=9ezWctMo39GPCd8BfDATZvBENRcD8NNgzHuDjGc8qEo&s=phPyUeKJKM2rVsG1aZytfwQo5i8zwxuPJEypWwU7vsA&e=>) which handles everything.

-Colin
