### ISSUE TITLE
key errors in the vignette

### ISSUE THREAD

**Issue by pat-s** [rundel/ghclass#80]
In https://rundel.github.io/ghclass/articles/ghclass.html#creating-teams

**Comment by rundel** [comment]
Thanks for the report, I hadn't noticed this was going on - something on GitHub's end is borked and preventing those teams from being created. I've but in a ticket to if we can get it resolved. Once that happens I'll push a rebuild pkgdown site.

**Comment by pat-s** [comment]
Just a follow-up that the error still exists in the vignette :)

**Comment by rundel** [comment]
Thanks, github's support has been less than helpful / responsive. I've gone ahead and changed how we labeled the homeworks so that everything should be working again.
